services:
  pastebin:
    image: mkaczanowski/pastebin:latest
    container_name: pastebin
    volumes:
      - $DOCKERDIR/pastebin:/var/lib/pastebin
    # Following Variables are optional, default values are shown. You can pass command line arguments directly as well, but not both.
    # environment:
    #   - PASTEBIN_ADDRESS=localhost # IP address or host to listen on
    #   - PASTEBIN_PORT=8000 # Port to listen on
    #   - PASTEBIN_ENVIRONMENT=production # Rocket server environment
    #   - PASTEBIN_WORKERS=0 # Number of concurrent thread workers
    #   - PASTEBIN_KEEP_ALIVE=5 # Keep-alive timeout in seconds
    #   - PASTEBIN_LOG_LEVEL=normal # Max log level
    #   - PASTEBIN_TTL=0 # Time to live for entries, by default '0# kept forever
    #   - PASTEBIN_DB_PATH=./pastebin.db # Database file path
    #   - PASTEBIN_TLS_CERTS_PATH="" # Path to certificate chain in PEM format
    #   - PASTEBIN_TLS_KEY="" # Path to private key for tls-certs in PEM format
    #   - PASTEBIN_URI="" # Override default URI
    #   - PASTEBIN_URI_PREFIX="" # Prefix appended to the URI (ie. '/pastebin')
    #   - PASTEBIN_SLUG_CHARSET="[A-Za-z0-9_-]" # Character set (expressed as rust compatible regex) to use for generating the URL slug
    #   - PASTEBIN_SLUG_LENGTH=21 # Length of URL slug
    #   - PASTEBIN_UI_EXPIRY_TIMES="5 minutes, 10 minutes, 1 hour, 1 day, 1 week, 1 month, 1 year, Never" # List of paste expiry times rendered in the UI dropdown selector
    #   - PASTEBIN_UI_LINE_NUMBERS=true # Display line numbers
    #   - PASTEBIN_PLUGINS=prism # Enable additional functionalities (ie. prism, mermaid)
    restart: unless-stopped
    # You can also pass command line arguments directly
    command: --address 0.0.0.0 --uri ${URI} --db=/var/lib/pastebin/
    # Uncomment below to expose pastebin service directly
    # ports:
    #   - 8000:8000
    healthcheck:
      test: sh -c 'ls -l /proc/*/exe | grep pastebin'
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s

  nginx:
    image: "nginx"
    ports:
      - "80:80"
    links:
      - pastebin:pastebin
    command: |
      bash -c "bash -s <<'EOF'
        cat > /etc/nginx/nginx.conf <<'EON'
          daemon off;
          error_log /dev/stderr info;

          events {
            worker_connections 768;
          }
            
          http {
            map $$sent_http_content_type $$expires {
                default                    off;
                text/css                   30d;
                application/javascript     30d;
                image/x-icon               30d;
            }

            server {
                listen       80; 
                server_name  0.0.0.0; 
                
                gzip on;
                gzip_types text/plain application/xml text/css application/javascript;
            
                expires $$expires;
                location / {
                    proxy_pass     http://pastebin:8000;
                    
                }
            
                access_log /dev/stdout;
            }
          }
      EON
      set -eux
      cat /etc/nginx/nginx.conf
      nginx 
      EOF"
