FROM mkaczanowski/archlinuxarm:armv7 as builder

RUN pacman -Sy --noconfirm rustup gcc llvm clang libclang \
    && pacman -Scc --noconfirm
RUN rustup default nightly

WORKDIR /usr/src/pastebin
COPY . .

RUN cargo install --path .

FROM mkaczanowski/archlinuxarm:armv7
RUN pacman -Sy --noconfirm glibc \
    && pacman -Scc --noconfirm
COPY --from=builder /root/.cargo/bin/pastebin /usr/local/bin/pastebin

ENTRYPOINT ["pastebin"]
CMD ["--help"]
